version: '3.1'

services:
  ghost:
    image: ghost:3-alpine
    restart: always
    ports:
      - 80:2368
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: dbpw
      database__connection__database: ghost
      # this url value is just an example, and is likely wrong for your environment!
      url: https://www.mcgillij.dev
    volumes:
      - ghost_apps:/var/www/ghost/content/apps
      - ghost_data:/var/www/ghost/content/data
      - ghost_images:/var/www/ghost/content/images
      - ghost_themes:/var/www/ghost/content/themes 

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dbpw

volumes:
  ghost_apps:
    driver: local
  ghost_data:
    driver: local
  ghost_images:
    driver: local
  ghost_themes:
    driver: local
